add codecov
ropensci/rif pull request #5
Opened 2017-02-17 23:36 UTC by steven2249

I am an rOpensci intern, working on adding test coverage components.

2017-03-14 19:28 UTC, sckott requested changes
nice work @steven2249 !

just a few things to change and then we're all good

2017-03-14 19:28 UTC, sckott commented on tests/testthat/test-lexical_sentences.R
> +test-that("lexical_sentences", {
@steven2249 this should be `test_that` not `test-that`

2017-03-14 19:28 UTC, sckott commented on tests/testthat/test-lexical_pmentities.R
> +  expect_equal(tt$start, c(0, 7, 45, 66))
@steven2249 running locally, the test on line 10 fails for me. check that one - I'm guessing that the value returned can vary through time - if so, remove that test, or change it to something that will pass no matter when it's called.

2017-03-15 02:37 UTC, steven2249 commented on tests/testthat/test-lexical_pmentities.R
> +  expect_equal(tt$start, c(0, 7, 45, 66))
removed

2017-03-15 02:38 UTC, steven2249 commented on tests/testthat/test-lexical_sentences.R
> +test-that("lexical_sentences", {
revised

2017-03-15 04:33 UTC, sckott approved these changes

2017-03-15 04:33 UTC, sckott commented
thanks @steven2249 !

this all looks good

2017-03-15 04:35 UTC, merged